---
language: generic

sudo: required

services:
  - docker

install:
  - docker --version

env:
  - IMAGE="nolith/ansible-test" VERSION="ubuntu_14.04"
  #- IMAGE="nolith/ansible-test" VERSION="ubuntu_12.04"

script:
  - uname -a
  - cat /etc/lsb-release
  - docker stop ansible || true
  - docker rm ansible || true
  - export IMAGE_FULL="${IMAGE}:${VERSION}"
  - docker pull ${IMAGE_FULL}
  - docker run --privileged -d --name ansible -v `pwd`:/data ${IMAGE_FULL}
  - docker exec -it ansible /bin/sh -c "ansible-galaxy install -v nolith.docker"
  - docker exec -it ansible /bin/sh -c "ansible-galaxy install -v nolith.docker_container"
  - docker exec -it ansible /bin/sh -c "ansible-playbook -v /data/test.yml -i localhost, -c local"
  #- ./tests/utils/run_test.sh

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
