---
language: generic

sudo: required

services:
  - docker

install:
  - docker --version

env:
  - IMAGE="nolith/ansible-test" VERSION="ubuntu_14.04"
  #- IMAGE="nolith/ansible-test" VERSION="ubuntu_12.04"

script:
  - uname -a
  - cat /etc/lsb-release
  #- ./tests/utils/run_test.sh

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
